package org.tellurgram;

import java.util.Arrays;

/**
 * Mercurygram: folds text written with decorated Unicode "fonts" down to plain ASCII, so that
 * searching for "Cucina italiana" finds a group actually named
 * "ℂᑌℂℐℕᗅ ℐᝨᗅℒℐᗅℕᗅ".
 *
 * Those alphabets come from two different places:
 *
 * - compatibility variants of the Latin letters (Letterlike Symbols, Mathematical Alphanumeric
 *   Symbols, fullwidth, circled, ...), which their NFKD decomposition maps back;
 * - unrelated scripts picked purely because a glyph looks like a Latin letter (Cherokee, Lisu,
 *   Canadian Aboriginal Syllabics, Tagbanwa, ...), which only a lookalike table can map.
 *
 * Both live in the one table below, generated offline. Decomposing on the device instead would
 * resolve against the device's own ICU, so the same APK would fold a name on a recent Android and
 * leave it alone on an older one - the OUTLINED LATIN alphabet (U+1CCD6.., Unicode 16.0) is
 * exactly what a font generator emits and exactly what an older phone has never heard of, and the
 * resulting "search does not find my chat" report is not reproducible on the maintainer's device.
 * A baked table can only ever be ahead of a device, never behind, since Unicode guarantees an
 * existing decomposition is never changed.
 *
 * The output feeds LocaleController.getTranslitString, whose own table covers precomposed Latin
 * characters only and walks the string one UTF-16 unit at a time, so it handles neither case
 * (Mathematical Alphanumerics are not even single UTF-16 units).
 */
public class MgUnicodeFold {

    /**
     * Every decorated codepoint followed by the ASCII it folds to, generated by
     * scripts/gen-unicode-fold.py: the confusables data (UTS #39,
     * https://www.unicode.org/Public/security/latest/confusables.txt) at version 17.0.0 for the
     * lookalikes, the decompositions of Unicode 16.0.0 for the compatibility variants. The script
     * prints both versions, so a regen that lands newer ones updates this line too; coverage is
     * frozen at them until it is rerun.
     *
     * No separator: a key is always above U+007F and a value is always ASCII, so an entry ends at
     * the next character too big to be a value. Both halves are packed the same way, and the
     * script checks that it can read its own output back before printing it.
     *
     * The decomposition half starts right above ASCII, at U+0080: the superscript alphabet a
     * generator emits mixes "⁰⁴..⁹" with "¹²³" and the ordinals "ª" / "º" sit next to "ᵃ" / "ᵒ", so
     * a cutoff at the end of Latin-1 would fold half of one alphabet. It maps a codepoint when
     * everything left after dropping the combining marks is ASCII. A non-ASCII base means real
     * text rather than decoration: Cyrillic "ё"
     * decomposes to "е" (which would break the upstream "ё" -> "yo" transliteration), Hangul
     * syllables decompose to jamo, kana lose their voicing mark, so those are left to the upstream
     * tables. A decomposition made of nothing but marks is left alone too, since folding it to the
     * empty string would delete the character.
     *
     * The lookalike half is filtered further, and the script documents that; in short an entry is
     * kept when the confusable target reduces to a single ASCII letter once its combining marks
     * are dropped and the upstream transliteration table does not already map it (its value wins
     * where they differ). It also starts at U+0100 rather than at U+0080, since below that the
     * upstream table owns the Latin letters and matching by glyph shape alone would map living
     * ones ("þ" to "p"). Scripts with a large living user base (Cyrillic, Greek, the Indic
     * family, CJK, ...) are left out on purpose: their letters are real text, not decoration, and
     * folding them would break both the Cyrillic transliteration the upstream table does and any
     * search in those scripts. Of Armenian, Arabic, Georgian and their neighbours only the letters
     * are left out: the digits are what the generators borrow ("۷" for "v"), and folding them is
     * symmetric, since getTranslitString runs over the search query as well as over the stored
     * name. A handful of entries are written by hand in the generator, either because the
     * confusables data has no entry at all (the Tagbanwa block) or because it resolves the glyph
     * to a prototype that is itself not ASCII; it documents which and why.
     *
     * Both cases of a bicameral letter are in the table even though the confusables data lists only
     * the one whose glyph looks Latin (Cherokee is there as "Ꭰ", never as "ꭰ"): every local search
     * lowercases before it transliterates, so the counterpart is the form that actually reaches
     * fold().
     */
    private static final String FOLD_PAIRS =
            "\u00a0\u0020¨\u0020ªa¯\u0020²2³3´\u0020¸\u0020¹1ºoÀa"
            + "ÁaÂaÃaÄaÅaÇcÈeÉeÊeËeÌi"
            + "ÍiÎiÏiÑnÒoÓoÔoÕoÖoÙuÚu"
            + "ÛuÜuÝyàaáaâaãaäaåaçcèe"
            + "éeêeëeìiíiîiïiñnòoóoôo"
            + "õoöoùuúuûuüuýyÿyĀaāaĂa"
            + "ăaĄaąaĆcćcĈcĉcĊcċcČcčc"
            + "ĎdďdĐdĒeēeĔeĕeĖeėeĘeęe"
            + "ĚeěeĜgĝgĞgğgĠgġgĢgģgĤh"
            + "ĥhĦhĨiĩiĪiīiĬiĭiĮiįiİi"
            + "ĲijĳijĴjĵjĶkķkĹlĺlĻlļlĽl"
            + "ľlŁlŃnńnŅnņnŇnňnŊnŋnŌo"
            + "ōoŎoŏoŐoőoŔrŕrŖrŗrŘrřr"
            + "ŚsśsŜsŝsŞsşsŠsšsŢtţtŤt"
            + "ťtŦtŨuũuŪuūuŬuŭuŮuůuŰu"
            + "űuŲuųuŴwŵwŶyŷyŸyŹzźzŻz"
            + "żzŽzžzſsƂbƄbƅbƉdƍgƑfƔy"
            + "ƖlƗlƝnƟoƠoơoƦrƮtƯuưuƵz"
            + "ƼsƽsƿpǀlǄdzǅdzǆdzǇljǈljǉljǊnj"
            + "ǋnjǌnjǍaǎaǏiǐiǑoǒoǓuǔuǕu"
            + "ǖuǗuǘuǙuǚuǛuǜuǞaǟaǠaǡa"
            + "ǤgǦgǧgǨkǩkǪoǫoǬoǭoǰjǱdz"
            + "ǲdzǳdzǴgǵgǷpǸnǹnǺaǻaǾoȀa"
            + "ȁaȂaȃaȄeȅeȆeȇeȈiȉiȊiȋi"
            + "ȌoȍoȎoȏoȐrȑrȒrȓrȔuȕuȖu"
            + "ȗuȘsșsȚtțtȞhȟhȤzȦaȧaȨe"
            + "ȩeȪoȫoȬoȭoȮoȯoȰoȱoȲyȳy"
            + "ȾtɄuɆeɈjɎyɑaɣyɩlʉuʰhʲj"
            + "ʳrʷwʸy˘\u0020˙\u0020˚\u0020˛\u0020˜\u0020˝\u0020ˡlˢs"
            + "ˣxͺ\u0020;;΄\u0020΅\u0020׀l١l٥o٧v۱l۵o"
            + "۷v߀o๐o໐o၀oᎠdᎡrᎢtᎤoᎥiᎩy"
            + "ᎪaᎫjᎬeᎱrᎳwᎷmᎻhᎽyᎾoᏀgᏂh"
            + "ᏃzᏌuᏏbᏒrᏔwᏕsᏙvᏚsᏞlᏟcᏢp"
            + "ᏦkᏧdᏫoᏲhᏳgᏴbᏺhᏻgᏼbᐯvᑌu"
            + "ᑭpᑯdᑲbᑳbᒍjᒪlᕁxᕼhᕽxᖇrᖯb"
            + "ᖴfᗅaᗞdᗪdᗰmᗷb᙭x᙮xᚷxᛁlᛕk"
            + "ᛖmᝨtᝪo០oᴦrᴬaᴮbᴰdᴱeᴳgᴴh"
            + "ᴵiᴶjᴷkᴸlᴹmᴺnᴼoᴾpᴿrᵀtᵁu"
            + "ᵂwᵃaᵇbᵈdᵉeᵍgᵏkᵐmᵒoᵖpᵗt"
            + "ᵘuᵛvᵢiᵣrᵤuᵥvᵻiᵼiᵾuᶜcᶠf"
            + "ᶻzḀaḁaḂbḃbḄbḅbḆbḇbḈcḉc"
            + "ḊdḋdḌdḍdḎdḏdḐdḑdḒdḓdḔe"
            + "ḕeḖeḗeḘeḙeḚeḛeḜeḝeḞfḟf"
            + "ḠgḡgḢhḣhḤhḥhḦhḧhḨhḩhḪh"
            + "ḫhḬiḭiḮiḯiḰkḱkḲkḳkḴkḵk"
            + "ḶlḷlḸlḹlḺlḻlḼlḽlḾmḿmṀm"
            + "ṁmṂmṃmṄnṅnṆnṇnṈnṉnṊnṋn"
            + "ṌoṍoṎoṏoṐoṑoṒoṓoṔpṕpṖp"
            + "ṗpṘrṙrṚrṛrṜrṝrṞrṟrṠsṡs"
            + "ṢsṣsṤsṥsṦsṧsṨsṩsṪtṫtṬt"
            + "ṭtṮtṯtṰtṱtṲuṳuṴuṵuṶuṷu"
            + "ṸuṹuṺuṻuṼvṽvṾvṿvẀwẁwẂw"
            + "ẃwẄwẅwẆwẇwẈwẉwẊxẋxẌxẍx"
            + "ẎyẏyẐzẑzẒzẓzẔzẕzẖhẗtẘw"
            + "ẙyẛsẠaạaẢaảaẤaấaẦaầaẨa"
            + "ẩaẪaẫaẬaậaẮaắaẰaằaẲaẳa"
            + "ẴaẵaẶaặaẸeẹeẺeẻeẼeẽeẾe"
            + "ếeỀeềeỂeểeỄeễeỆeệeỈiỉi"
            + "ỊiịiỌoọoỎoỏoỐoốoỒoồoỔo"
            + "ổoỖoỗoỘoộoỚoớoỜoờoỞoởo"
            + "ỠoỡoỢoợoỤuụuỦuủuỨuứuỪu"
            + "ừuỬuửuỮuữuỰuựuỲyỳyỴyỵy"
            + "ỶyỷyỸyỹy᾽\u0020᾿\u0020῀\u0020῁\u0020῍\u0020῎\u0020῏\u0020"
            + "῝\u0020῞\u0020῟\u0020῭\u0020΅\u0020``´\u0020῾\u0020\u2000\u0020\u2001\u0020\u2002\u0020"
            + "\u2003\u0020\u2004\u0020\u2005\u0020\u2006\u0020\u2007\u0020\u2008\u0020\u2009\u0020\u200a\u0020‗\u0020․.‥.."
            + "…...\u202f\u0020‼!!‾\u0020⁇??⁈?!⁉!?\u205f\u0020⁰0ⁱi⁴4"
            + "⁵5⁶6⁷7⁸8⁹9⁺+⁼=⁽(⁾)ⁿn₀0"
            + "₁1₂2₃3₄4₅5₆6₇7₈8₉9₊+₌="
            + "₍(₎)ₐaₑeₒoₓxₕhₖkₗlₘmₙn"
            + "ₚpₛsₜt₡c₨rs₩w₫d₭k₮t℀a/c℁a/s"
            + "ℂc℅c/o℆c/uℊgℋhℌhℍhℎhℏhℐiℑi"
            + "ℒlℓlℕn№noℙpℚqℛrℜrℝr℠sm℡tel"
            + "™tmℤzℨzKkÅaℬbℭc℮eℯeℰeℱf"
            + "ℳmℴoℹi℻faxℽyⅅdⅆdⅇeⅈiⅉjⅠi"
            + "ⅡiiⅢiiiⅣivⅤvⅥviⅦviiⅧviiiⅨixⅩxⅪxiⅫxii"
            + "ⅬlⅭcⅮdⅯmⅰiⅱiiⅲiiiⅳivⅴvⅵviⅶvii"
            + "ⅷviiiⅸixⅹxⅺxiⅻxiiⅼlⅽcⅾdⅿm∣l∨v"
            + "∪u≠=≮<≯>⊖o⊝o⊤t⋁v⋃u⋿e⍡t"
            + "⍬o⍳i⍴p⍶a⍸i⍺a⏽l①1②2③3④4"
            + "⑤5⑥6⑦7⑧8⑨9⑩10⑪11⑫12⑬13⑭14⑮15"
            + "⑯16⑰17⑱18⑲19⑳20⑴(1)⑵(2)⑶(3)⑷(4)⑸(5)⑹(6)"
            + "⑺(7)⑻(8)⑼(9)⑽(10)⑾(11)⑿(12)⒀(13)⒁(14)⒂(15)⒃(16)⒄(17)"
            + "⒅(18)⒆(19)⒇(20)⒈1.⒉2.⒊3.⒋4.⒌5.⒍6.⒎7.⒏8."
            + "⒐9.⒑10.⒒11.⒓12.⒔13.⒕14.⒖15.⒗16.⒘17.⒙18.⒚19."
            + "⒛20.⒜(a)⒝(b)⒞(c)⒟(d)⒠(e)⒡(f)⒢(g)⒣(h)⒤(i)⒥(j)"
            + "⒦(k)⒧(l)⒨(m)⒩(n)⒪(o)⒫(p)⒬(q)⒭(r)⒮(s)⒯(t)⒰(u)"
            + "⒱(v)⒲(w)⒳(x)⒴(y)⒵(z)ⒶaⒷbⒸcⒹdⒺeⒻf"
            + "ⒼgⒽhⒾiⒿjⓀkⓁlⓂmⓃnⓄoⓅpⓆq"
            + "ⓇrⓈsⓉtⓊuⓋvⓌwⓍxⓎyⓏzⓐaⓑb"
            + "ⓒcⓓdⓔeⓕfⓖgⓗhⓘiⓙjⓚkⓛlⓜm"
            + "ⓝnⓞoⓟpⓠqⓡrⓢsⓣtⓤuⓥvⓦwⓧx"
            + "ⓨyⓩz⓪0╳x⟙t⤫x⤬x⨯x⨰x⩴::=⩵=="
            + "⩶===ⱧhⱩkⱭaⱼjⱽvⲂbⲃbⲄrⲅrⲆa"
            + "ⲇaⲈeⲉeⲊsⲋsⲎhⲏhⲐoⲑoⲒlⲓi"
            + "ⲔkⲕkⲘmⲙmⲚnⲛnⲞoⲟoⲢpⲣpⲤc"
            + "ⲥcⲦtⲧtⲨyⲩyⲬxⲭxⲼwⲽwⳎpⳏp"
            + "Ⳑlⳑlⴱoⴸvⴹeⵁoⵏlⵔoⵕqⵝx\u3000\u0020"
            + "〇o゛\u0020゜\u0020㉐pte㉑21㉒22㉓23㉔24㉕25㉖26㉗27"
            + "㉘28㉙29㉚30㉛31㉜32㉝33㉞34㉟35㊱36㊲37㊳38"
            + "㊴39㊵40㊶41㊷42㊸43㊹44㊺45㊻46㊼47㊽48㊾49"
            + "㊿50㋌hg㋍erg㋎ev㋏ltd㍱hpa㍲da㍳au㍴bar㍵ov㍶pc"
            + "㍷dm㍸dm2㍹dm3㍺iu㎀pa㎁na㎃ma㎄ka㎅kb㎆mb㎇gb"
            + "㎈cal㎉kcal㎊pf㎋nf㎎mg㎏kg㎐hz㎑khz㎒mhz㎓ghz㎔thz"
            + "㎖ml㎗dl㎘kl㎙fm㎚nm㎜mm㎝cm㎞km㎟mm2㎠cm2㎡m2"
            + "㎢km2㎣mm3㎤cm3㎥m3㎦km3㎩pa㎪kpa㎫mpa㎬gpa㎭rad㎰ps"
            + "㎱ns㎳ms㎴pv㎵nv㎷mv㎸kv㎹mv㎺pw㎻nw㎽mw㎾kw"
            + "㎿mw㏂a.m.㏃bq㏄cc㏅cd㏇co.㏈db㏉gy㏊ha㏋hp㏌in"
            + "㏍kk㏎km㏏kt㏐lm㏑ln㏒log㏓lx㏔mb㏕mil㏖mol㏗ph"
            + "㏘p.m.㏙ppm㏚pr㏛sr㏜sv㏝wb㏿galꓐbꓑpꓒdꓓd"
            + "ꓔtꓖgꓗkꓙjꓚcꓜzꓝfꓟmꓠnꓡlꓢs"
            + "ꓣrꓦvꓧhꓪwꓫxꓬyꓮaꓰeꓲlꓳoꓴu"
            + "ꛟvꝀkꝊoꞘfꞙfꞞuꞟuꞲjꞳxꞴbꞵb"
            + "ꟲcꟳfꟴqꬲeꬵfꬽoꬾoꭇrꭈrꭎuꭒu"
            + "ꭓxꭚyꭰdꭱrꭲtꭴoꭵiꭹyꭺaꭻjꭼe"
            + "ꮁrꮃwꮇmꮋhꮍyꮎoꮐgꮒhꮓzꮜuꮟb"
            + "ꮢrꮤwꮥsꮩvꮪsꮮlꮯcꮲpꮶkꮷdꮻo"
            + "ﬀffﬁfiﬂflﬃffiﬄfflﬅstﬆst﬩+ﱞ\u0020ﱟ\u0020ﱠ\u0020"
            + "ﱡ\u0020ﱢ\u0020ﱣ\u0020︐,︓:︔;︕!︖?︙...︰..︳_"
            + "︴_︵(︶)︷{︸}﹇[﹈]﹉\u0020﹊\u0020﹋\u0020﹌\u0020"
            + "﹍_﹎_﹏_﹐,﹒.﹔;﹕:﹖?﹗!﹙(﹚)"
            + "﹛{﹜}﹟#﹠&﹡*﹢+﹣-﹤<﹥>﹦=﹨\\"
            + "﹩$﹪%﹫@ﹰ\u0020ﹲ\u0020ﹴ\u0020ﹶ\u0020ﹸ\u0020ﹺ\u0020ﹼ\u0020ﹾ\u0020"
            + "！!＂\"＃#＄$％%＆&＇'（(）)＊*＋+"
            + "，,－-．.／/０0１1２2３3４4５5６6"
            + "７7８8９9：:；;＜<＝=＞>？?＠@Ａa"
            + "ＢbＣcＤdＥeＦfＧgＨhＩiＪjＫkＬl"
            + "ＭmＮnＯoＰpＱqＲrＳsＴtＵuＶvＷw"
            + "ＸxＹyＺz［[＼\\］]＾^＿_｀`ａaｂb"
            + "ｃcｄdｅeｆfｇgｈhｉiｊjｋkｌlｍm"
            + "ｎnｏoｐpｑqｒrｓsｔtｕuｖvｗwｘx"
            + "ｙyｚz｛{｜|｝}～~￣\u0020￨l𐆎n𐆖x𐆗v"
            + "𐊂b𐊆e𐊇f𐊊l𐊐x𐊒o𐊕p𐊖s𐊗t𐊠a𐊡b"
            + "𐊢c𐊥f𐊫o𐊰m𐊱t𐊲y𐊴x𐋏h𐋵z𐌁b𐌂c"
            + "𐌉l𐌑m𐌕t𐌗x𐌠l𐌢x𐐄o𐐕c𐐛l𐐠s𐐬o"
            + "𐐽c𐑃l𐑈s𐒴r𐓂o𐓎u𐓜r𐓪o𐓶u𐔓n𐔖o"
            + "𐔘k𐔜c𐔝v𐔥f𐔦l𐔧x𐞥q𑓐o𑜆v𑜊w𑜎w"
            + "𑜏w𑢠v𑢡s𑢢f𑢣l𑢤y𑢦e𑢨o𑢩z𑢮e𑢲l"
            + "𑢵o𑢷o𑢸u𑢼t𑣀v𑣁s𑣂f𑣃i𑣄z𑣆e𑣈o"
            + "𑣉z𑣎e𑣒l𑣕o𑣗o𑣘u𑣜y𑣠o𑣥z𑣦w𑣩c"
            + "𑣬x𑣯w𑣲c\ud807\udddal\ud807\udde0o\ud807\udde1l\ud81b\udeaal\ud81b\udeb6b𖼈v𖼊t𖼖l"
            + "𖼨l𖼵r𖼺s𖽀a𖽂u𖽃y𜳖a𜳗b𜳘c𜳙d𜳚e"
            + "𜳛f𜳜g𜳝h𜳞i𜳟j𜳠k𜳡l𜳢m𜳣n𜳤o𜳥p"
            + "𜳦q𜳧r𜳨s𜳩t𜳪u𜳫v𜳬w𜳭x𜳮y𜳯z𜳰0"
            + "𜳱1𜳲2𜳳3𜳴4𜳵5𜳶6𜳷7𜳸8𜳹9𝈍v𝈓f"
            + "𝈖r𝈚o𝈪l𝐀a𝐁b𝐂c𝐃d𝐄e𝐅f𝐆g𝐇h"
            + "𝐈i𝐉j𝐊k𝐋l𝐌m𝐍n𝐎o𝐏p𝐐q𝐑r𝐒s"
            + "𝐓t𝐔u𝐕v𝐖w𝐗x𝐘y𝐙z𝐚a𝐛b𝐜c𝐝d"
            + "𝐞e𝐟f𝐠g𝐡h𝐢i𝐣j𝐤k𝐥l𝐦m𝐧n𝐨o"
            + "𝐩p𝐪q𝐫r𝐬s𝐭t𝐮u𝐯v𝐰w𝐱x𝐲y𝐳z"
            + "𝐴a𝐵b𝐶c𝐷d𝐸e𝐹f𝐺g𝐻h𝐼i𝐽j𝐾k"
            + "𝐿l𝑀m𝑁n𝑂o𝑃p𝑄q𝑅r𝑆s𝑇t𝑈u𝑉v"
            + "𝑊w𝑋x𝑌y𝑍z𝑎a𝑏b𝑐c𝑑d𝑒e𝑓f𝑔g"
            + "𝑖i𝑗j𝑘k𝑙l𝑚m𝑛n𝑜o𝑝p𝑞q𝑟r𝑠s"
            + "𝑡t𝑢u𝑣v𝑤w𝑥x𝑦y𝑧z𝑨a𝑩b𝑪c𝑫d"
            + "𝑬e𝑭f𝑮g𝑯h𝑰i𝑱j𝑲k𝑳l𝑴m𝑵n𝑶o"
            + "𝑷p𝑸q𝑹r𝑺s𝑻t𝑼u𝑽v𝑾w𝑿x𝒀y𝒁z"
            + "𝒂a𝒃b𝒄c𝒅d𝒆e𝒇f𝒈g𝒉h𝒊i𝒋j𝒌k"
            + "𝒍l𝒎m𝒏n𝒐o𝒑p𝒒q𝒓r𝒔s𝒕t𝒖u𝒗v"
            + "𝒘w𝒙x𝒚y𝒛z𝒜a𝒞c𝒟d𝒢g𝒥j𝒦k𝒩n"
            + "𝒪o𝒫p𝒬q𝒮s𝒯t𝒰u𝒱v𝒲w𝒳x𝒴y𝒵z"
            + "𝒶a𝒷b𝒸c𝒹d𝒻f𝒽h𝒾i𝒿j𝓀k𝓁l𝓂m"
            + "𝓃n𝓅p𝓆q𝓇r𝓈s𝓉t𝓊u𝓋v𝓌w𝓍x𝓎y"
            + "𝓏z𝓐a𝓑b𝓒c𝓓d𝓔e𝓕f𝓖g𝓗h𝓘i𝓙j"
            + "𝓚k𝓛l𝓜m𝓝n𝓞o𝓟p𝓠q𝓡r𝓢s𝓣t𝓤u"
            + "𝓥v𝓦w𝓧x𝓨y𝓩z𝓪a𝓫b𝓬c𝓭d𝓮e𝓯f"
            + "𝓰g𝓱h𝓲i𝓳j𝓴k𝓵l𝓶m𝓷n𝓸o𝓹p𝓺q"
            + "𝓻r𝓼s𝓽t𝓾u𝓿v𝔀w𝔁x𝔂y𝔃z𝔄a𝔅b"
            + "𝔇d𝔈e𝔉f𝔊g𝔍j𝔎k𝔏l𝔐m𝔑n𝔒o𝔓p"
            + "𝔔q𝔖s𝔗t𝔘u𝔙v𝔚w𝔛x𝔜y𝔞a𝔟b𝔠c"
            + "𝔡d𝔢e𝔣f𝔤g𝔥h𝔦i𝔧j𝔨k𝔩l𝔪m𝔫n"
            + "𝔬o𝔭p𝔮q𝔯r𝔰s𝔱t𝔲u𝔳v𝔴w𝔵x𝔶y"
            + "𝔷z𝔸a𝔹b𝔻d𝔼e𝔽f𝔾g𝕀i𝕁j𝕂k𝕃l"
            + "𝕄m𝕆o𝕊s𝕋t𝕌u𝕍v𝕎w𝕏x𝕐y𝕒a𝕓b"
            + "𝕔c𝕕d𝕖e𝕗f𝕘g𝕙h𝕚i𝕛j𝕜k𝕝l𝕞m"
            + "𝕟n𝕠o𝕡p𝕢q𝕣r𝕤s𝕥t𝕦u𝕧v𝕨w𝕩x"
            + "𝕪y𝕫z𝕬a𝕭b𝕮c𝕯d𝕰e𝕱f𝕲g𝕳h𝕴i"
            + "𝕵j𝕶k𝕷l𝕸m𝕹n𝕺o𝕻p𝕼q𝕽r𝕾s𝕿t"
            + "𝖀u𝖁v𝖂w𝖃x𝖄y𝖅z𝖆a𝖇b𝖈c𝖉d𝖊e"
            + "𝖋f𝖌g𝖍h𝖎i𝖏j𝖐k𝖑l𝖒m𝖓n𝖔o𝖕p"
            + "𝖖q𝖗r𝖘s𝖙t𝖚u𝖛v𝖜w𝖝x𝖞y𝖟z𝖠a"
            + "𝖡b𝖢c𝖣d𝖤e𝖥f𝖦g𝖧h𝖨i𝖩j𝖪k𝖫l"
            + "𝖬m𝖭n𝖮o𝖯p𝖰q𝖱r𝖲s𝖳t𝖴u𝖵v𝖶w"
            + "𝖷x𝖸y𝖹z𝖺a𝖻b𝖼c𝖽d𝖾e𝖿f𝗀g𝗁h"
            + "𝗂i𝗃j𝗄k𝗅l𝗆m𝗇n𝗈o𝗉p𝗊q𝗋r𝗌s"
            + "𝗍t𝗎u𝗏v𝗐w𝗑x𝗒y𝗓z𝗔a𝗕b𝗖c𝗗d"
            + "𝗘e𝗙f𝗚g𝗛h𝗜i𝗝j𝗞k𝗟l𝗠m𝗡n𝗢o"
            + "𝗣p𝗤q𝗥r𝗦s𝗧t𝗨u𝗩v𝗪w𝗫x𝗬y𝗭z"
            + "𝗮a𝗯b𝗰c𝗱d𝗲e𝗳f𝗴g𝗵h𝗶i𝗷j𝗸k"
            + "𝗹l𝗺m𝗻n𝗼o𝗽p𝗾q𝗿r𝘀s𝘁t𝘂u𝘃v"
            + "𝘄w𝘅x𝘆y𝘇z𝘈a𝘉b𝘊c𝘋d𝘌e𝘍f𝘎g"
            + "𝘏h𝘐i𝘑j𝘒k𝘓l𝘔m𝘕n𝘖o𝘗p𝘘q𝘙r"
            + "𝘚s𝘛t𝘜u𝘝v𝘞w𝘟x𝘠y𝘡z𝘢a𝘣b𝘤c"
            + "𝘥d𝘦e𝘧f𝘨g𝘩h𝘪i𝘫j𝘬k𝘭l𝘮m𝘯n"
            + "𝘰o𝘱p𝘲q𝘳r𝘴s𝘵t𝘶u𝘷v𝘸w𝘹x𝘺y"
            + "𝘻z𝘼a𝘽b𝘾c𝘿d𝙀e𝙁f𝙂g𝙃h𝙄i𝙅j"
            + "𝙆k𝙇l𝙈m𝙉n𝙊o𝙋p𝙌q𝙍r𝙎s𝙏t𝙐u"
            + "𝙑v𝙒w𝙓x𝙔y𝙕z𝙖a𝙗b𝙘c𝙙d𝙚e𝙛f"
            + "𝙜g𝙝h𝙞i𝙟j𝙠k𝙡l𝙢m𝙣n𝙤o𝙥p𝙦q"
            + "𝙧r𝙨s𝙩t𝙪u𝙫v𝙬w𝙭x𝙮y𝙯z𝙰a𝙱b"
            + "𝙲c𝙳d𝙴e𝙵f𝙶g𝙷h𝙸i𝙹j𝙺k𝙻l𝙼m"
            + "𝙽n𝙾o𝙿p𝚀q𝚁r𝚂s𝚃t𝚄u𝚅v𝚆w𝚇x"
            + "𝚈y𝚉z𝚊a𝚋b𝚌c𝚍d𝚎e𝚏f𝚐g𝚑h𝚒i"
            + "𝚓j𝚔k𝚕l𝚖m𝚗n𝚘o𝚙p𝚚q𝚛r𝚜s𝚝t"
            + "𝚞u𝚟v𝚠w𝚡x𝚢y𝚣z𝚤i𝚨a𝚩b𝚬e𝚭z"
            + "𝚮h𝚯o𝚰l𝚱k𝚳m𝚴n𝚶o𝚸p𝚹o𝚻t𝚼y"
            + "𝚾x𝛂a𝛄y𝛈n𝛉o𝛊i𝛎v𝛐o𝛒p𝛔o𝛖u"
            + "𝛝o𝛠p𝛢a𝛣b𝛦e𝛧z𝛨h𝛩o𝛪l𝛫k𝛭m"
            + "𝛮n𝛰o𝛲p𝛳o𝛵t𝛶y𝛸x𝛼a𝛾y𝜂n𝜃o"
            + "𝜄i𝜈v𝜊o𝜌p𝜎o𝜐u𝜗o𝜚p𝜜a𝜝b𝜠e"
            + "𝜡z𝜢h𝜣o𝜤l𝜥k𝜧m𝜨n𝜪o𝜬p𝜭o𝜯t"
            + "𝜰y𝜲x𝜶a𝜸y𝜼n𝜽o𝜾i𝝂v𝝄o𝝆p𝝈o"
            + "𝝊u𝝑o𝝔p𝝖a𝝗b𝝚e𝝛z𝝜h𝝝o𝝞l𝝟k"
            + "𝝡m𝝢n𝝤o𝝦p𝝧o𝝩t𝝪y𝝬x𝝰a𝝲y𝝶n"
            + "𝝷o𝝸i𝝼v𝝾o𝞀p𝞂o𝞄u𝞋o𝞎p𝞐a𝞑b"
            + "𝞔e𝞕z𝞖h𝞗o𝞘l𝞙k𝞛m𝞜n𝞞o𝞠p𝞡o"
            + "𝞣t𝞤y𝞦x𝞪a𝞬y𝞰n𝞱o𝞲i𝞶v𝞸o𝞺p"
            + "𝞼o𝞾u𝟅o𝟈p𝟊f𝟎0𝟏1𝟐2𝟑3𝟒4𝟓5"
            + "𝟔6𝟕7𝟖8𝟗9𝟘0𝟙1𝟚2𝟛3𝟜4𝟝5𝟞6"
            + "𝟟7𝟠8𝟡9𝟢0𝟣1𝟤2𝟥3𝟦4𝟧5𝟨6𝟩7"
            + "𝟪8𝟫9𝟬0𝟭1𝟮2𝟯3𝟰4𝟱5𝟲6𝟳7𝟴8"
            + "𝟵9𝟶0𝟷1𝟸2𝟹3𝟺4𝟻5𝟼6𝟽7𝟾8𝟿9"
            + "𞣇l𞸀l𞸤o𞹤o𞺀l𞺄o🄀0.🄁0,🄂1,🄃2,🄄3,"
            + "🄅4,🄆5,🄇6,🄈7,🄉8,🄊9,🄐(a)🄑(b)🄒(c)🄓(d)🄔(e)"
            + "🄕(f)🄖(g)🄗(h)🄘(i)🄙(j)🄚(k)🄛(l)🄜(m)🄝(n)🄞(o)🄟(p)"
            + "🄠(q)🄡(r)🄢(s)🄣(t)🄤(u)🄥(v)🄦(w)🄧(x)🄨(y)🄩(z)🄫c"
            + "🄬r🄭cd🄮wz🄰a🄱b🄲c🄳d🄴e🄵f🄶g🄷h"
            + "🄸i🄹j🄺k🄻l🄼m🄽n🄾o🄿p🅀q🅁r🅂s"
            + "🅃t🅄u🅅v🅆w🅇x🅈y🅉z🅊hv🅋mv🅌sd🅍ss"
            + "🅎ppv🅏wc🅪mc🅫md🅬mr🆐dj🜈v🜔o🝌c🝨t🯰0"
            + "🯱1🯲2🯳3🯴4🯵5🯶6🯷7🯸8🯹9";


    // The table parsed once into two parallel arrays, the keys ascending, so a lookup is a binary
    // search with no boxing on the miss path - which is what almost every character is, and
    // getTranslitString runs per keystroke over every dialog name and over every message indexed
    // for search. KEYS is package-private so the test can check the table's shape without walking
    // the whole codepoint space.
    static final int[] KEYS;
    private static final String[] VALUES;

    static {
        final int len = FOLD_PAIRS.length();
        int count = 0;
        for (int i = 0; i < len; ) {
            final int cp = FOLD_PAIRS.codePointAt(i);
            i += Character.charCount(cp);
            // a key is what starts an entry, the ASCII after it is the value
            if (cp >= 0x80) {
                count++;
            }
        }
        KEYS = new int[count];
        VALUES = new String[count];
        int entry = 0;
        for (int i = 0; i < len; ) {
            final int cp = FOLD_PAIRS.codePointAt(i);
            i += Character.charCount(cp);
            final int valueStart = i;
            while (i < len && FOLD_PAIRS.charAt(i) < 0x80) {
                i++;
            }
            KEYS[entry] = cp;
            VALUES[entry] = FOLD_PAIRS.substring(valueStart, i);
            entry++;
        }
    }

    /**
     * Returns {@code src} normalized for local search: every decorated codepoint replaced by the
     * plain lowercase ASCII it stands for, every combining mark dropped and every symbol turned
     * into a space (see {@link #undecorate}). Plain characters, and characters from scripts we
     * have no mapping for, are returned untouched - case included, so ASCII text comes back
     * identical and the very same instance is returned when nothing needed folding.
     *
     * The result is meant for matching, never for display: it is what search compares against,
     * not a transliteration of the name.
     */
    public static String fold(String src) {
        StringBuilder dst = null;
        final int len = src.length();
        for (int i = 0; i < len; ) {
            final int cp = src.codePointAt(i);
            String replacement = null;
            // Below the first key there is nothing to look up and nothing to undecorate either,
            // and that is what almost every character of a name is.
            if (cp >= KEYS[0]) {
                final int entry = Arrays.binarySearch(KEYS, cp);
                replacement = entry >= 0 ? VALUES[entry] : undecorate(cp);
            }
            if (replacement == null) {
                if (dst != null) {
                    dst.appendCodePoint(cp);
                }
            } else {
                if (dst == null) {
                    dst = new StringBuilder(len).append(src, 0, i);
                }
                dst.append(replacement);
            }
            i += Character.charCount(cp);
        }
        return dst == null ? src : dst.toString();
    }

    /**
     * What a codepoint the table has no entry for becomes, or null to keep it as it is.
     *
     * A combining mark is decoration wherever it sits - the table drops the ones its own values
     * carried for the same reason - so it is dropped rather than left to separate a word from the
     * query that should have matched it.
     *
     * A symbol becomes a space, because local search only ever matches a query at the start of a
     * word: MessagesStorage.localSearch tests startsWith(query) and contains(" " + query). A name
     * decorated as "♥️cucina❤️italiana" has the emoji glued straight onto the word, so without a
     * separator the only reachable word would be the first one, and that one starts with the emoji.
     * This only ever affects the transliterated copy the search compares against, never what the
     * user sees.
     */
    static String undecorate(int cp) {
        switch (Character.getType(cp)) {
            case Character.NON_SPACING_MARK:
            case Character.ENCLOSING_MARK:
            case Character.FORMAT:
                return "";
            case Character.MATH_SYMBOL:
            case Character.CURRENCY_SYMBOL:
            case Character.MODIFIER_SYMBOL:
            case Character.OTHER_SYMBOL:
                return " ";
            default:
                return null;
        }
    }
}
